name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  verify-links:
    name: Check for dead links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git fetch origin master
          git merge origin/master
          
      - name: Install MarkdownLinkChecker
        run: dotnet tool install -g markdownlinkchecker

      - name: Verify links
        run: |
          deleted_or_renamed=$(git diff --no-commit-id --name-only --diff-filter DR origin/master | grep  -i .md$ | grep -v -i _sidebar.md | grep -v -i ISSUE_TEMPLATE | wc -l)

          if [ "$GITHUB_REF" = "refs/heads/master" ] || [ $deleted_or_renamed -ne 0 ]
          then
              echo "::debug::Searching all files..."
              files=$(find . -name \*.md ! -iname _sidebar.md ! -ipath \*/ISSUE_TEMPLATE/\*.md -not -path "./.git/*")
          else
              echo "::debug::Searching changed files..."
              files=$(git diff --no-commit-id --name-only --diff-filter AM origin/master | grep  -i .md$ | grep -v -i _sidebar.md | grep -v -i ISSUE_TEMPLATE | cat)
          fi

          dotnet markdownlinkchecker -v detailed -f "$files"
